# Generated by Django 3.2.13 on 2022-09-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220901_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_at',
            new_name='updated_time',
        ),
    ]
