# Generated by Django 3.2.15 on 2022-08-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220831_1348'),
        ('articles', '0002_auto_20220831_1354'),
    ]

    operations = [
    ]
